#!perl

use strict;
use warnings;

use OrePAN2::Auditor ();
my $outdated = OrePAN2::Auditor->new_with_options;
$outdated->run;

__END__

=head1 NAME

orepan2-audit - 02packages auditor

=head1 SYNOPSIS

    % orepan2-audit --show outdated-releases --verbose --darkpan path/to/darkpan/02packages --cpan http://cpan.metacpan.org/modules/02packages.details.txt

=head1 DESCRIPTION

OrePAN2 auditor.  This script finds differences between your DarkPAN and a CPAN mirror.

=head1 OPTIONS

=over 4

=item C< --show >

Possible values are C<outdated-releases>, C<outdated-modules>, C<cpan-only-modules> and C<darkpan-only-modules>.

=item C< --darkpan >

The full path or URL to a DarkPAN 02packages file in .txt or .txt.gz format.

=item C< --cpan >

The full path or URL to a CPAN 02packages file in .txt or .txt.gz format.

=item C< --verbose >

Print out some version information.  Currenly only applies to outdated modules

=back
