#!/usr/bin/env perl
use strict;
use warnings;
use OrePAN2::CLI::Inject;

OrePAN2::CLI::Inject->new->run(@ARGV);

__END__

=head1 NAME

orepan2-inject - Injector

=head1 SYNOPSIS

    % orepan2-inject git://github.com/miyagawa/Acme-YakiniQ.git@master /path/to/darkpan/
    % orepan2-inject Carton /path/to/darkpan/

=head1 DESCRIPTION

OrePAN2 injector. This module injects your modules into the OrePAN2 DarkPAN repository.

=head1 OPTIONS

=over 4

=item C< --no-generate-index >

Do not generate I<02packages.details.txt.gz>.

=item C< --author=DANKOGAI >

Specify the cpan author directory name.

OrePAN2 uses 'DUMMY' as a default author name.

=item C< --simple >

Use a simple format for 02packages metadata.  This helps avoid merge conflicts.

=back

=head1 SOURCES

orepan2-inject script supports following source types.

=head2 ARCHIVE FILE

    orepan2-inject Text-TestBase-0.10.tar.gz /path/to/darkpan/

You can inject into DarkPAN from a file.

=head2 HTTP URL

    orepan2-inject http://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Text-TestBase-0.10.tar.gz /path/to/darkpan/

You can inject into DarkPAN from an archive URL.

=head2 Git repository

    % orepan2-inject git://github.com/miyagawa/Acme-YakiniQ.git@master /path/to/darkpan/
    % orepan2-inject git://github.com/miyagawa/Acme-YakiniQ.git        /path/to/darkpan/

You need to set up git repository as a installable git repo.
You need to put a META.json in your repository.

If you are using Minilla or Milla, your repository is already ready to install.

OrePAN2::Inject supports the following URL types:

    git+file://path/to/repo.git
    git://github.com/plack/Plack.git@1.0000        # tag
    git://github.com/plack/Plack.git@devel         # branch

It's compatible with cpanm.

=head2 Module name

    % orepan2-inject Data::Dumper /path/to/darkpan

You can inject from CPAN by module name.

