---
name: Build and Test
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    container:
      image: perldocker/perl-tester:5.38
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests with coverage
        env:
          AUTHOR_TESTING: 1
          AUTOMATED_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
        run: auto-build-and-test-dist
      - uses: actions/upload-artifact@v4
        with:
          name: build_dir
          path: build_dir
  test_linux:
    runs-on: ubuntu-latest
    name: Test distribution
    needs: build
    strategy:
      matrix:
        perl-version:
          - "5.14"
          - "5.16"
          - "5.18"
          - "5.20"
          - "5.22"
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"
          - "5.32"
          - "5.34"
          - "5.36"
          - "5.38"
          - "5.40"
          - "5.42"
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build_dir
          path: .
      - name: Install deps and test
        if: success()
        env:
          AUTHOR_TESTING: 1
          RELEASE_TESTING: 1
        run: cpan-install-dist-deps && test-dist
  test_macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.14"
          - "5.16"
          - "5.18"
          - "5.20"
          - "5.22"
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"
          - "5.32"
          - "5.34"
          - "5.36"
          - "5.38"
          - "5.40"
          - "5.42"
    name: Perl ${{ matrix.perl-version }} on macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - uses: actions/download-artifact@master
        with:
          name: build_dir
          path: .
      - name: install deps using cpm
        uses: perl-actions/install-with-cpm@v1.9
        with:
          cpanfile: "cpanfile"
          args: "--with-suggests --with-recommends --with-test"
      - run: prove -lr t
        if: success()
